apollo:
    bootstrap:
        eagerLoad:
            enabled: true
        enabled: true
    meta: http://127.0.0.1:8080
# apollo应用id
app:
    id: skyeye-kaiyuan
server:
    port: ${server.port}
    tomcat:
        uri-encoding: utf-8
    context-path: /

#数据源
spring:
    datasource:
        jdbc-url: jdbc:mysql://localhost:3306/${jdbc.database.name}?useUnicode=true&characterEncoding=utf8
        driver-class-name: ${jdbc.database.driverClassName}
        username: ${jdbc.database.username}
        password: ${jdbc.database.password}
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        #下面为连接池的补充设置，应用到上面所有数据源中
        #初始化大小，最小，最大
        maxActive: ${jdbc.maxActive}
        initialSize: ${jdbc.initialSize}
        maxWait: ${jdbc.maxWait}
        minIdle: ${jdbc.minIdle}
        #打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: ${jdbc.poolPreparedStatements}
        maxPoolPreparedStatementPerConnectionSize: ${jdbc.maxPoolPreparedStatementPerConnectionSize}
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        #配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        
        activiti:
            # 自动部署验证设置:true-开启（默认）、false-关闭
            check-process-definitions: false
            url: jdbc:mysql://localhost:3306/${activiti.database.name}?useUnicode=true&characterEncoding=utf8&useSSL=false
            username: ${activiti.database.username}
            password: ${activiti.database.password}
            driver-class-name: com.mysql.jdbc.Driver
            type: com.alibaba.druid.pool.DruidDataSource
        

#热部署配置
devtools:
restart:
    #热部署生效
    enabled: true
    #启用/禁用自动配置更改的记录
    log-condition-evaluation-delta: false
    #排除那个目录的文件不需要restart
    exclude: template/**
    #添加那个目录的文件需要restart
    additional-paths: src/main/java

mvc:
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
servlet:
    multipart:
        max-file-size: 100Mb
        max-request-size: 100Mb
        
#redis集群
redis:
    clusterNodes: ${redis.ip1}:${redis.host1},${redis.ip2}:${redis.host2},${redis.ip3}:${redis.host3},${redis.ip4}:${redis.host4},${redis.ip5}:${redis.host5},${redis.ip6}:${redis.host6}
    #连接超时时间（毫秒）
    timeout: 10000
    #redis操作的超时时间
    commandTimeout: 10000
    pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 2
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100

